"""
boilerplate.py — GÉNÉRÉ, ne pas éditer à la main.

Produit par tools/detecter_boilerplate.py à partir de
archive.jsonl : pour chaque source, le pied de page que ses
articles recopient à l'identique.

Un texte identique d'un article à l'autre d'une même source ne
peut pas être le contenu de cet article-là. C'est ce qui
permet de le retirer sans connaître un seul mot de vocabulaire.
"""

# nom de la source -> suffixe à retirer de ses corps
BOILERPLATE_PAR_SOURCE: dict[str, str] = {
    'Asia-Plus': 'in the field of prevention, detection, and response to CBRN threats. Uzbekistan introduces fines for teachers over violence against children asia+ - The document was adopted against the backdrop of a series of scandals involving teachers beating schoolchildren 35 years on the road: How migration has changed Tajikistan Сайфиддин Караев - How have the reasons, destinations, and the very portrait of the Tajik migrant changed? Gorbunov high-altitude station modernized on Tajikistan Glacier Сайфиддин Караев - After the modernization, hydrometeorological data began to be received from it again. The National Interest: New US sanctions on Iran could affect Tajikistan Сайфиддин Караев - The risks are primarily associated with fuel supplies, banking settlements, and transportation through Iran. Central Asia’s women media professionals gather in Tashkent asia+ - Central Asian female journalists will discuss digital threats and AI Somon Air receives second Boeing 737 MAX 8 asia+ - The new liner was named after Abuabdullo Rudaki Mijgona Samadova named Tajikistan’s flag bearer at 2026 Asian Games Алексей Корчагин - The roster of the Tajikistan national team for the XX Summer Asian Games, which will be held from September 19 to October 4 in Japan, has been determined. Uzbekistan to increase minimum fine for excessive household noise ninefold asia+ - The amendments also establish new quiet hours, restrictions on construction work, and sanctions against systematic violators. Load more',
    '24.kg — russe': 'Популярные новости За 10 дней из России в Узбекистан вернулись почти 100 тысяч граждан страны «Врачи боятся работать». Коллектив НЦОМиД обратился к Садыру Жапарову «Главное, чтобы показали». Бекешев раскритиковал посадки деревьев для отчетов «Письмо 75»: суд переквалифицировал статью и назначил два года пробации Бизнес ЖК Tianshan-1 изнутри: ход строительства и качество работ показали вживую Новый учебный год — новый смартфон: как выгодно обновить устройство При финансовой поддержке Госбанка развития запущена еще одна малая ГЭС DemirBank продолжает наращивать инвестиции в Кыргызстан Лента новостей 14 сентября, понедельник 18:05 В Узбекистане хотят отвязать алименты от зарплаты и учитывать потребности детей В Узбекистане хотят отвязать алименты от зарплаты и учи... 17:45 На одного из участников драки на рынке «Баткен» в Бишкеке составили протокол 17:25 Читатель пожаловался на мусор в горах на лыжной базе Оруу-Сай 17:18 Внешняя торговля Кыргызстана достигла 10 миллиардов долларов 17:04 Кыргызстан и Пакистан открывают новый маршрут для грузового транзита 16:56 Кыргызстан получит грант до $50 миллионов на зеленую энергетику 16:47 Ушел из дома и не вернулся. Родные разыскивают 62-летнего Чортека Мамбеталиева 16:30 В Кыргызстане назвали стоимость километра двух- и четырехполосной дорог 16:27 ЖК Tianshan-1 изнутри: ход строительства и качество работ показали вживую 16:04 Мост на две страны: у КПП «Бедель» построят 56-метровый переход',
    'Daryo.uz': "in taxes in 8M26 Today, 15:02 Uzbekistan proposes industrial cooperation program with South Korea, Central Asian states Today, 14:01 Uzbekistan’s bank deposits rise 34% to $41.1bn Today, 13:00 Uzbekistan’s Mirziyoyev calls for new production systems as Korean investment tops $8bn Today, 12:00 Uzbekistan, Finland explore cooperation in governance, digitalization and climate issues Today, 11:00 Recommendations 1 Uzbekistan 35 years of independence: Uzbekistan through foreign eyes 11:00 / 31.08.2026 2 Uzbekistan Uzbekistan's fixed capital investment grows 17.5% in 1H26 15:30 / 30.07.2026 3 Uzbekistan Uzbekistan's industrial output rises 8% to $53.3bn in 1H26 14:00 / 30.07.2026 4 Uzbekistan Uzbekistan's logistics hub potential depends on infrastructure and reforms, says Jasurbek Choriyev 17:00 / 07.07.2026 5 Uzbekistan Uzbekistan's annual inflation rises to 6.4% in June on higher utility and transport costs 12:02 / 06.07.2026 6 Uzbekistan Uzbekistan’s foreign trade turnover reaches $32.8bn in Jan–May 2026, up 3.7% y/y 12:00 / 01.07.2026 Menu Good news: Uzbekistan Central Asia World Money Culture Sport Lifestyle Tags About Daryo Privacy policy About Daryo Editorial office Contact us Terms of use News archive Grow your business with us Advertise on Daryo.uz Place an ad Individual approach and exclusive materials Ad-free site reading Subscribe 25 000 sum per month Social Networks: Latest News Recommendations",
    'Kremlin.ru': 'устройств Разделы сайта Президента России События Структура Видео и фото Документы Контакты Поиск Поиск Для СМИ Подписаться Справочник Версия для людей с ограниченными возможностями English Информационные ресурсы Президента России Президент России Текущий ресурс Конституция России Государственная символика Обратиться к Президенту Президент России — гражданам школьного возраста Виртуальный тур по Кремлю Владимир Путин — личный сайт Дикая природа России Официальные сетевые ресурсы Президента России MAX ВКонтакте Rutube Telegram-канал YouTube Правовая и техническая информация О портале Об использовании информации сайта О персональных данных пользователей Написать в редакцию Все материалы сайта доступны по лицензии: Creative Commons Attribution 4.0 International Администрация Президента России 2026 год Официальные сетевые ресурсы Президента России Official Internet Resources of the President of Russia Русский English Для СМИ Специальная версия для людей с ограниченными возможностями MAX ВКонтакте Rutube Telegram-канал YouTube Сайт Президента России Конституция России Государственная символика Обратиться к Президенту Президент России — гражданам школьного возраста Виртуальный тур по Кремлю Владимир Путин — личный сайт Путин. 20 лет Дикая природа России Администрация Президента России 2026 год',
    '24.kg — anglais': "Popular Kyrgyzstan prints 20- and 50-som banknotes domestically for first time Antimonopoly Service announces agreed fuel and lubricants prices Kyrgyzstan to introduce EMPIC GmbH software for flight safety oversight Bishkek City Court sentences nephrologist Beishebaeva to 3 years in prison News brief 14 September, Monday 18:54 Kyrgyzstan and Pakistan open new route for freight transit Kyrgyzstan and Pakistan open new route for freight tran... 18:49 Kyrgyzstan to receive up to $50M grant for green energy 18:43 56-meter bridge to be built at Bedel checkpoint on Kyrgyz-Chinese border 18:11 Sadyr Japarov to pay official visit to South Korea 18:06 Russia becomes main supplier of mineral water to Kyrgyzstan 17:49 Two workers killed at construction site in Manas 17:42 5,854 people are held in Kyrgyzstan's correctional facilities 17:34 Kyrgyzstan’s Parliament gets 91st member: Locally made robot becomes guide 17:23 Accounts Chamber auditor: $25 million loan to Alfa Oil was ineffective 16:09 Kyrgyzstan proposes round-the-clock operations for Torugart checkpoint",
    'Vlast — russe': 'финпирамиды Finiko Новости Таиланд сокращает срок безвизового пребывания для граждан Казахстана Новости Дожди, ветер и понижение температуры прогнозируются в Казахстане в ближайшие дни На аль-Фараби в Алматы в районе Esentai Mall ввели ограничения для транспорта на перестроение Новости Казахстанцы могут онлайн записаться на прием к депутатам курултая Новости Аким Атырау ушел с должности Просматриваемые Новости 08.09.2026 Суд Алматы вынес приговор пятерым активистам по делу о попытке захвата Акорды Новости 08.09.2026 Казахстан откажется от 12-летнего образования в школах Новости 07.09.2026 Дожди прогнозируются в Казахстане в ближайшие три дня Новости 09.09.2026 В Алматы и Алматинской области с 12 сентября повысятся тарифы на электроэнергию Новости 11.09.2026 Кассационный суд оставил в силе отказ в статусе беженца чеченскому активисту Мансуру Мовлаеву Новости 11.09.2026 SkyTrain в Алматы начнут строить в следующем году',
    'The Guardian — Kazakhstan': 'Most viewed Across the guardian Sydney Sweeney under fire for ‘sexualising women’s sport’ in sports prediction ad UK ministers urged to act after US flies out diplomat accused of possessing indecent images of children US schools and police warn about viral ‘Cat in the Hat’ trend after teens’ arrests Satellite images show extent of damage to major Saudi pipeline, amid global oil supply fears Missing US hiker, 70, found injured on remote island after week-long search Indonesian foragers may have sucked on mind-altering nuts 25,000 years ago, research finds New Charlie Kirk statue vandalized at Turning Point USA headquarters The pet I’ll never forget: Polly, the golden retriever who saved my husband’s life The situation in Iran is dangerously escalating – but whatever you do, don’t call it a war A little rudeness can save you from being scammed? Count me in',
    'Central Asia-Caucasus Analyst': 'back to top Visit also The Central Asia-Caucasus Analyst is a biweekly publication of the Central Asia-Caucasus Institute & Silk Road Studies Program, a Joint Transatlantic Research and Policy Center affiliated with the American Foreign Policy Council, Washington DC., and the Institute for Security and Development Policy, Stockholm. For 15 years, the Analyst has brought cutting edge analysis of the region geared toward a practitioner audience. Article Tags Afghanistan Armenia Azerbaijan Central Asia China Georgia Iran Kazakhstan Kyrgyzstan Pakistan Russia South Caucasus Tajikistan United States Uzbekistan Newsletter Sign up for upcoming events, latest news, and articles from the CACI Analyst. Newsletter The Central Asia-Caucasus Institute and Silk Road Studies Program Joint Center',
    'CGTN': 'Filipino French Français German Deutsch Greek Ελληνικά Hausa Hausa Hebrew עברית Hungarian Magyar Hindi हिन्दी Indonesian Bahasa Indonesia Italian Italiano Japanese 日本語 Korean 한국어 Lao ລາວ Malay Bahasa Melayu Mongolian Монгол Myanmar မြန်မာဘာသာ Nepali नेपाली Persian فارسی Polish Polski Portuguese Português Pashto پښتو Romanian Română Russian Русский Serbian Српски Sinhalese සිංහල Spanish Español Swahili Kiswahili Tamil தமிழ் Thai ไทย Turkish Türkçe Ukrainian Українська Urdu اردو Vietnamese Tiếng Việt FOLLOW CGTN DOWNLOAD OUR APP Terms of use Copyright Privacy policy About us Copyright © 2026 CGTN. 京ICP备20000184号 京公网安备 11010502050052号 互联网新闻信息许可证10120180008 Disinformation report hotline: 010-85061466',
    'China Daily': 'MOBILE Copyright 1994 - . All rights reserved. The content (including but not limited to text, photo, multimedia information, etc) published in this site belongs to China Daily Information Co (CDIC). Without written authorization from CDIC, such content shall not be republished or used in any form. Note: Browsers with 1024*768 or higher resolution are suggested for this site. License for publishing multimedia online 0108263 Registration Number: 130349 About China Daily Advertise on Site Contact Us Job Offer Expat Employment FOLLOW US',
    'OSCE': 'Contacts Željka Šulc Mission Spokesperson OSCE Mission to Bosnia and Herzegovina Press and Public Information Unit Fra Anđela Zvizdovića 1, UNITIC Tower A 71000 Sarajevo Bosnia & Herzegovina Email: press.ba@osce.org Phone: + 387 (0)33 952 238 Contact OSCE Mission to Bosnia and Herzegovina Fra Anđela Zvizdovića 1, UNITIC Tower A 71000 Sarajevo Bosnia & Herzegovina Phone: +387 33 952 100 Email: info.ba@osce.org press.ba@osce.org Social media: @oscebih @oscebih @oscebih @oscebih',
    'Vlast — anglais': 'Sign up for our English-language newsletter . Власть — это независимое медиа в Казахстане. Поддержите журналистику, которой доверяют. Мы верим, что справедливое общество невозможно построить без независимой журналистики и достоверной информации. Наша редакция работает над тем чтобы правда была доступна для наших читателей на фоне большой волны фейков, манипуляций и пропаганды. Поддержите Власть. Поддержать Власть',
    'Azernews': 'Here we are to serve you with news right now. It does not cost much, but worth your attention. Choose to support open, independent, quality journalism and subscribe on a monthly basis. By subscribing to our online newspaper, you can have full digital access to all news, analysis, and much more. Subscribe You can also follow AzerNEWS on Twitter @AzerNewsAz or Facebook @AzerNewsNewspaper Thank you!',
    'SpecialEurasia': 'Unless explicit attribution to an author or rights holder is provided, the imagery published herein was generated using artificial intelligence technology In assenza di esplicita attribuzione di paternità o di proprietà intellettuale, i contenuti visivi pubblicati devono considerarsi prodotti mediante l’impiego di tecnologie di intelligenza artificiale',
    'Ministère russe des Affaires étrangères': 'Консульский портал Архивная служба Для СМИ Полезная информация Открытые данные Противодействие коррупции Об использовании информации сайта Технические сведения О персональных данных пользователей Министерство иностранных дел Российской Федерации © Министерство иностранных дел Российской Федерации Поделиться ссылкой на выделенное',
    'Radio Azattyq': 'Бөлісу Сілтемесін көшіру Facebook X (Twitter) WhatsApp Email Бөлісу Бөлісу Сілтемесін көшіру Facebook X (Twitter) WhatsApp Email Бөлісу PDF VPN-сіз оқу Сайт бұғатталып тұрса да, материалды осы сілтемемен кіріп оқуға болады Follow us Facebook X (Twitter) Youtube Instagram Follow us Принтерден шығару Айдар ЖАҢАЛЫҚТАР ЖАЛПЫ АРХИВ',
    'Cabar.asia': '‘This publication was funded by the European Union. Its contents are the sole responsibility of IWPR and do not necessarily reflect the views of the European Union. Download If you have found a spelling error, please, notify us by selecting that text and pressing Ctrl+Enter .',
    'Kloop': 'ЭТО МОЖЕТ БЫТЬ ИНТЕРЕСНО ЕЩЕ ОТ АВТОРА Медведь в объятиях дракона. Как Китай наступает на позиции России в Центральной Азии Кара-Сууйский рынок передают Управделами президента Финансовые нарушения на 826 млн сомов в бюджете Балыкчы. Городом руководит родственник Туманбаева',
    'Novastan — allemand': 'Entschlüsselung Kirgistans offene Daten Kirgistans offene Daten Im gleichen Jahr waren in Deutschland und in Frankreich je 49 Prozent und 63 Prozent der wichtigsten Datensätze verfügbar. In der neuesten Ausgabe des Rankings ist Kirgistan... Tweets by Novastan_Fr Kommentare',
    'Institute for European Politics': 'Newsletter Karriere Netiquette Impressum Datenschutzerklärung Erklärung zur Barrierefreiheit Institut für Europäische Politik e.V. Bundesallee 23, 10717 Berlin +49 30 88 913 40 info@iep-berlin.de',
    'USCIRF': 'View Hearings USCIRF Events During 2019 Ministerial July 16, 2019 2018 Ministerial to Advance Religious Freedom July 25, 2018 View Ministerial to Advance Religious Freedom',
}
