"""
pays_monde.py — GÉNÉRÉ, ne pas éditer à la main.

Produit par tools/generer_pays.py à partir de pycountry
(ISO 3166-1 et ses traductions officielles fr/ru).

La morphologie russe et les formes familières des pays de la zone
de veille restent curées à la main dans categorisation.py, qui a
la priorité sur cette table.
"""

# terme normalisé -> identifiant de pays
PAYS_MONDE_TERMES: dict[str, str] = {
    'afrique du sud': 'afrique_du_sud',
    'albania': 'albanie',
    'albanie': 'albanie',
    'algeria': 'algerie',
    'algérie': 'algerie',
    'allemagne': 'allemagne',
    'american samoa': 'samoa_americaines',
    'andorra': 'andorre',
    'andorre': 'andorre',
    'angola': 'angola',
    'anguilla': 'anguilla',
    'antarctica': 'antarctique',
    'antarctique': 'antarctique',
    'antigua and barbuda': 'antigua_et_barbuda',
    'antigua-et-barbuda': 'antigua_et_barbuda',
    'arab republic of egypt': 'egypte',
    'arabie saoudite': 'arabie_saoudite',
    'argentina': 'argentine',
    'argentine': 'argentine',
    'argentine republic': 'argentine',
    'aruba': 'aruba',
    'australia': 'australie',
    'australie': 'australie',
    'austria': 'autriche',
    'autriche': 'autriche',
    'bahamas': 'bahamas',
    'bahrain': 'bahrein',
    'bahreïn': 'bahrein',
    'bangladesh': 'bangladesh',
    'barbade': 'barbade',
    'barbados': 'barbade',
    'belgique': 'belgique',
    'belgium': 'belgique',
    'belize': 'belize',
    'benin': 'benin',
    'bermuda': 'bermudes',
    'bermudes': 'bermudes',
    'bhoutan': 'bhoutan',
    'bhutan': 'bhoutan',
    'birmanie': 'birmanie',
    'bolivarian republic of venezuela': 'venezuela_republique_bolivarienne_du',
    'bolivia': 'bolivie_etat_plurinational_de',
    'bolivia, plurinational state of': 'bolivie_etat_plurinational_de',
    'bolivie, état plurinational de': 'bolivie_etat_plurinational_de',
    'bonaire, saint-eustache et saba': 'bonaire_saint_eustache_et_saba',
    'bonaire, sint eustatius and saba': 'bonaire_saint_eustache_et_saba',
    'bosnia and herzegovina': 'bosnie_herzegovine',
    'bosnie-herzégovine': 'bosnie_herzegovine',
    'botswana': 'botswana',
    'bouvet island': 'ile_bouvet',
    'brazil': 'bresil',
    'british indian ocean territory': 'territoire_britannique_de_l_ocean_indien',
    'british virgin islands': 'iles_vierges_britanniques',
    'brunei darussalam': 'brunei_darussalam',
    'brunéi darussalam': 'brunei_darussalam',
    'brésil': 'bresil',
    'bulgaria': 'bulgarie',
    'bulgarie': 'bulgarie',
    'burkina faso': 'burkina_faso',
    'burundi': 'burundi',
    'bénin': 'benin',
    'cabo verde': 'cap_vert',
    'cambodge': 'cambodge',
    'cambodia': 'cambodge',
    'cameroon': 'cameroun',
    'cameroun': 'cameroun',
    'canada': 'canada',
    'cap-vert': 'cap_vert',
    'cayman islands': 'iles_caimans',
    'central african republic': 'republique_centrafricaine',
    'chile': 'chili',
    'chili': 'chili',
    'christmas island': 'christmas_ile',
    'christmas, île': 'christmas_ile',
    'chypre': 'chypre',
    'cocos (keeling) islands': 'cocos_keeling_iles',
    'cocos (keeling), îles': 'cocos_keeling_iles',
    'colombia': 'colombie',
    'colombie': 'colombie',
    'commonwealth of dominica': 'dominique',
    'commonwealth of the bahamas': 'bahamas',
    'commonwealth of the northern mariana islands': 'iles_mariannes_du_nord',
    'comores': 'comores',
    'comoros': 'comores',
    'congo': 'republique_du_congo',
    'congo, the democratic republic of the': 'republique_democratique_du_congo',
    'cook islands': 'iles_cook',
    'corée, république de': 'coree_republique_de',
    'corée, république populaire démocratique de': 'coree_republique_populaire_democratique_de',
    'costa rica': 'costa_rica',
    'croatia': 'croatie',
    'croatie': 'croatie',
    'cuba': 'cuba',
    'curaçao': 'curacao',
    'cyprus': 'chypre',
    'czech republic': 'tchequie',
    'czechia': 'tchequie',
    "côte d'ivoire": 'cote_d_ivoire',
    'danemark': 'danemark',
    "democratic people's republic of korea": 'coree_republique_populaire_democratique_de',
    'democratic republic of sao tome and principe': 'sao_tome_et_principe',
    'democratic republic of timor-leste': 'timor_oriental',
    'democratic socialist republic of sri lanka': 'sri_lanka',
    'denmark': 'danemark',
    'djibouti': 'djibouti',
    'dominica': 'dominique',
    'dominican republic': 'republique_dominicaine',
    'dominique': 'dominique',
    'eastern republic of uruguay': 'uruguay',
    'ecuador': 'equateur',
    'egypt': 'egypte',
    'el salvador': 'salvador',
    'equatorial guinea': 'guinee_equatoriale',
    'eritrea': 'erythree',
    'espagne': 'espagne',
    'estonia': 'estonie',
    'estonie': 'estonie',
    'eswatini': 'eswatini',
    'ethiopia': 'ethiopie',
    'falkland islands (malvinas)': 'malouines_iles_falkland',
    'faroe islands': 'iles_feroe',
    'federal democratic republic of ethiopia': 'ethiopie',
    'federal democratic republic of nepal': 'nepal',
    'federal republic of germany': 'allemagne',
    'federal republic of nigeria': 'nigeria',
    'federal republic of somalia': 'somalie',
    'federated states of micronesia': 'micronesie_etats_federes_de',
    'federative republic of brazil': 'bresil',
    'fidji': 'fidji',
    'fiji': 'fidji',
    'finland': 'finlande',
    'finlande': 'finlande',
    'france': 'france',
    'french guiana': 'guyane_francaise',
    'french polynesia': 'polynesie_francaise',
    'french republic': 'france',
    'french southern territories': 'terres_australes_francaises',
    'gabon': 'gabon',
    'gabonese republic': 'gabon',
    'gambia': 'gambie',
    'gambie': 'gambie',
    'germany': 'allemagne',
    'ghana': 'ghana',
    'gibraltar': 'gibraltar',
    'grand duchy of luxembourg': 'luxembourg',
    'greece': 'grece',
    'greenland': 'groenland',
    'grenada': 'grenade',
    'grenade': 'grenade',
    'groënland': 'groenland',
    'grèce': 'grece',
    'guadeloupe': 'guadeloupe',
    'guam': 'guam',
    'guatemala': 'guatemala',
    'guernesey': 'guernesey',
    'guernsey': 'guernesey',
    'guinea-bissau': 'guinee_bissau',
    'guinée': 'guinee',
    'guinée équatoriale': 'guinee_equatoriale',
    'guinée-bissau': 'guinee_bissau',
    'guyana': 'guyana',
    'guyane française': 'guyane_francaise',
    'géorgie du sud et les îles sandwich du sud': 'georgie_du_sud_et_les_iles_sandwich_du_sud',
    'haiti': 'haiti',
    'hashemite kingdom of jordan': 'jordanie',
    'haïti': 'haiti',
    'heard island and mcdonald islands': 'iles_heard_et_macdonald',
    'hellenic republic': 'grece',
    'holy see (vatican city state)': 'saint_siege_etat_de_la_cite_du_vatican',
    'honduras': 'honduras',
    'hong kong': 'hong_kong',
    'hong kong special administrative region of china': 'hong_kong',
    'hongrie': 'hongrie',
    'hungary': 'hongrie',
    'iceland': 'islande',
    'inde': 'inde',
    'independent state of papua new guinea': 'papouasie_nouvelle_guinee',
    'independent state of samoa': 'samoa',
    'india': 'inde',
    'indonesia': 'indonesie',
    'indonésie': 'indonesie',
    'irak': 'irak',
    'iraq': 'irak',
    'ireland': 'irlande',
    'irlande': 'irlande',
    'islamic republic of mauritania': 'mauritanie',
    'islamic republic of pakistan': 'pakistan',
    'islande': 'islande',
    'isle of man': 'ile_de_man',
    'israel': 'israel',
    'israël': 'israel',
    'italian republic': 'italie',
    'italie': 'italie',
    'italy': 'italie',
    'jamaica': 'jamaique',
    'jamaïque': 'jamaique',
    'japan': 'japon',
    'japon': 'japon',
    'jersey': 'jersey',
    'jordanie': 'jordanie',
    'kenya': 'kenya',
    'kingdom of bahrain': 'bahrein',
    'kingdom of belgium': 'belgique',
    'kingdom of bhutan': 'bhoutan',
    'kingdom of cambodia': 'cambodge',
    'kingdom of denmark': 'danemark',
    'kingdom of eswatini': 'eswatini',
    'kingdom of lesotho': 'lesotho',
    'kingdom of morocco': 'maroc',
    'kingdom of norway': 'norvege',
    'kingdom of saudi arabia': 'arabie_saoudite',
    'kingdom of spain': 'espagne',
    'kingdom of sweden': 'suede',
    'kingdom of thailand': 'thailande',
    'kingdom of the netherlands': 'pays_bas',
    'kingdom of tonga': 'tonga',
    'kiribati': 'kiribati',
    "korea, democratic people's republic of": 'coree_republique_populaire_democratique_de',
    'korea, republic of': 'coree_republique_de',
    'koweït': 'koweit',
    'kuwait': 'koweit',
    "lao people's democratic republic": 'lao_republique_democratique_populaire',
    'lao, république démocratique populaire': 'lao_republique_democratique_populaire',
    'laos': 'lao_republique_democratique_populaire',
    'latvia': 'lettonie',
    'lebanese republic': 'liban',
    'lebanon': 'liban',
    'lesotho': 'lesotho',
    'lettonie': 'lettonie',
    'liban': 'liban',
    'liberia': 'liberia',
    'libya': 'libye',
    'libye': 'libye',
    'libéria': 'liberia',
    'liechtenstein': 'liechtenstein',
    'lithuania': 'lituanie',
    'lituanie': 'lituanie',
    'luxembourg': 'luxembourg',
    'macao': 'macau',
    'macao special administrative region of china': 'macau',
    'macau': 'macau',
    'macédoine du nord': 'macedoine_du_nord',
    'madagascar': 'madagascar',
    'malaisie': 'malaisie',
    'malawi': 'malawi',
    'malaysia': 'malaisie',
    'maldives': 'maldives',
    'malouines, îles (falkland)': 'malouines_iles_falkland',
    'malta': 'malte',
    'malte': 'malte',
    'maroc': 'maroc',
    'marshall islands': 'iles_marshall',
    'martinique': 'martinique',
    'maurice': 'maurice',
    'mauritania': 'mauritanie',
    'mauritanie': 'mauritanie',
    'mauritius': 'maurice',
    'mayotte': 'mayotte',
    'mexico': 'mexique',
    'mexique': 'mexique',
    'micronesia, federated states of': 'micronesie_etats_federes_de',
    'micronésie, états fédérés de': 'micronesie_etats_federes_de',
    'monaco': 'monaco',
    'mongolia': 'mongolie',
    'mongolie': 'mongolie',
    'montenegro': 'montenegro',
    'montserrat': 'montserrat',
    'monténégro': 'montenegro',
    'morocco': 'maroc',
    'mozambique': 'mozambique',
    'myanmar': 'birmanie',
    'namibia': 'namibie',
    'namibie': 'namibie',
    'nauru': 'nauru',
    'nepal': 'nepal',
    'netherlands': 'pays_bas',
    'new caledonia': 'nouvelle_caledonie',
    'new zealand': 'nouvelle_zelande',
    'nicaragua': 'nicaragua',
    'niger': 'niger',
    'nigeria': 'nigeria',
    'nioue': 'nioue',
    'niue': 'nioue',
    'norfolk island': 'ile_norfolk',
    'north korea': 'coree_republique_populaire_democratique_de',
    'north macedonia': 'macedoine_du_nord',
    'northern mariana islands': 'iles_mariannes_du_nord',
    'norvège': 'norvege',
    'norway': 'norvege',
    'nouvelle-calédonie': 'nouvelle_caledonie',
    'nouvelle-zélande': 'nouvelle_zelande',
    'népal': 'nepal',
    'oman': 'oman',
    'ouganda': 'ouganda',
    'pakistan': 'pakistan',
    'palaos': 'palaos',
    'palau': 'palaos',
    'palestine, state of': 'palestine_etat_de',
    'palestine, état de': 'palestine_etat_de',
    'panama': 'panama',
    'papouasie-nouvelle-guinée': 'papouasie_nouvelle_guinee',
    'papua new guinea': 'papouasie_nouvelle_guinee',
    'paraguay': 'paraguay',
    'pays-bas': 'pays_bas',
    "people's democratic republic of algeria": 'algerie',
    "people's republic of bangladesh": 'bangladesh',
    'peru': 'perou',
    'philippines': 'philippines',
    'pitcairn': 'iles_pitcairn',
    'plurinational state of bolivia': 'bolivie_etat_plurinational_de',
    'poland': 'pologne',
    'pologne': 'pologne',
    'polynésie française': 'polynesie_francaise',
    'porto rico': 'porto_rico',
    'portugal': 'portugal',
    'portuguese republic': 'portugal',
    'principality of andorra': 'andorre',
    'principality of liechtenstein': 'liechtenstein',
    'principality of monaco': 'monaco',
    'puerto rico': 'porto_rico',
    'pérou': 'perou',
    'qatar': 'qatar',
    'republic of albania': 'albanie',
    'republic of angola': 'angola',
    'republic of austria': 'autriche',
    'republic of benin': 'benin',
    'republic of bosnia and herzegovina': 'bosnie_herzegovine',
    'republic of botswana': 'botswana',
    'republic of bulgaria': 'bulgarie',
    'republic of burundi': 'burundi',
    'republic of cabo verde': 'cap_vert',
    'republic of cameroon': 'cameroun',
    'republic of chad': 'tchad',
    'republic of chile': 'chili',
    'republic of colombia': 'colombie',
    'republic of costa rica': 'costa_rica',
    'republic of croatia': 'croatie',
    'republic of cuba': 'cuba',
    'republic of cyprus': 'chypre',
    "republic of côte d'ivoire": 'cote_d_ivoire',
    'republic of djibouti': 'djibouti',
    'republic of ecuador': 'equateur',
    'republic of el salvador': 'salvador',
    'republic of equatorial guinea': 'guinee_equatoriale',
    'republic of estonia': 'estonie',
    'republic of fiji': 'fidji',
    'republic of finland': 'finlande',
    'republic of ghana': 'ghana',
    'republic of guatemala': 'guatemala',
    'republic of guinea': 'guinee',
    'republic of guinea-bissau': 'guinee_bissau',
    'republic of guyana': 'guyana',
    'republic of haiti': 'haiti',
    'republic of honduras': 'honduras',
    'republic of iceland': 'islande',
    'republic of india': 'inde',
    'republic of indonesia': 'indonesie',
    'republic of iraq': 'irak',
    'republic of kenya': 'kenya',
    'republic of kiribati': 'kiribati',
    'republic of latvia': 'lettonie',
    'republic of liberia': 'liberia',
    'republic of lithuania': 'lituanie',
    'republic of madagascar': 'madagascar',
    'republic of malawi': 'malawi',
    'republic of maldives': 'maldives',
    'republic of mali': 'mali',
    'republic of malta': 'malte',
    'republic of mauritius': 'maurice',
    'republic of mozambique': 'mozambique',
    'republic of myanmar': 'birmanie',
    'republic of namibia': 'namibie',
    'republic of nauru': 'nauru',
    'republic of nicaragua': 'nicaragua',
    'republic of north macedonia': 'macedoine_du_nord',
    'republic of palau': 'palaos',
    'republic of panama': 'panama',
    'republic of paraguay': 'paraguay',
    'republic of peru': 'perou',
    'republic of poland': 'pologne',
    'republic of san marino': 'saint_marin',
    'republic of senegal': 'senegal',
    'republic of serbia': 'serbie',
    'republic of seychelles': 'seychelles',
    'republic of sierra leone': 'sierra_leone',
    'republic of singapore': 'singapour',
    'republic of slovenia': 'slovenie',
    'republic of south africa': 'afrique_du_sud',
    'republic of south sudan': 'soudan_du_sud',
    'republic of suriname': 'surinam',
    'republic of the congo': 'republique_du_congo',
    'republic of the gambia': 'gambie',
    'republic of the marshall islands': 'iles_marshall',
    'republic of the niger': 'niger',
    'republic of the philippines': 'philippines',
    'republic of the sudan': 'soudan',
    'republic of trinidad and tobago': 'trinite_et_tobago',
    'republic of tunisia': 'tunisie',
    'republic of uganda': 'ouganda',
    'republic of vanuatu': 'vanuatu',
    'republic of yemen': 'yemen',
    'republic of zambia': 'zambie',
    'republic of zimbabwe': 'zimbabwe',
    'romania': 'roumanie',
    'roumanie': 'roumanie',
    'royaume-uni': 'royaume_uni',
    'rwanda': 'rwanda',
    'rwandese republic': 'rwanda',
    'république centrafricaine': 'republique_centrafricaine',
    'république dominicaine': 'republique_dominicaine',
    'république du congo': 'republique_du_congo',
    'république démocratique du congo': 'republique_democratique_du_congo',
    'réunion': 'reunion_ile_de_la',
    'réunion, île de la': 'reunion_ile_de_la',
    'sahara occidental': 'sahara_occidental',
    'saint barthélemy': 'saint_barthelemy',
    'saint helena, ascension and tristan da cunha': 'sainte_helene_ascension_et_tristan_da_cunha',
    'saint kitts and nevis': 'saint_christophe_et_nieves',
    'saint lucia': 'sainte_lucie',
    'saint martin (french part)': 'saint_martin_partie_francaise',
    'saint pierre and miquelon': 'saint_pierre_et_miquelon',
    'saint vincent and the grenadines': 'saint_vincent_et_les_grenadines',
    'saint-barthélemy': 'saint_barthelemy',
    'saint-christophe-et-niévès': 'saint_christophe_et_nieves',
    'saint-marin': 'saint_marin',
    'saint-martin (partie française)': 'saint_martin_partie_francaise',
    'saint-martin (partie néerlandaise)': 'saint_martin_partie_neerlandaise',
    'saint-pierre-et-miquelon': 'saint_pierre_et_miquelon',
    'saint-siège (état de la cité du vatican)': 'saint_siege_etat_de_la_cite_du_vatican',
    'saint-vincent-et-les-grenadines': 'saint_vincent_et_les_grenadines',
    'sainte-hélène, ascension et tristan da cunha': 'sainte_helene_ascension_et_tristan_da_cunha',
    'sainte-lucie': 'sainte_lucie',
    'salomon, îles': 'salomon_iles',
    'salvador': 'salvador',
    'samoa': 'samoa',
    'samoa américaines': 'samoa_americaines',
    'san marino': 'saint_marin',
    'sao tome and principe': 'sao_tome_et_principe',
    'sao tomé-et-principe': 'sao_tome_et_principe',
    'saudi arabia': 'arabie_saoudite',
    'senegal': 'senegal',
    'serbia': 'serbie',
    'serbie': 'serbie',
    'seychelles': 'seychelles',
    'sierra leone': 'sierra_leone',
    'singapore': 'singapour',
    'singapour': 'singapour',
    'sint maarten (dutch part)': 'saint_martin_partie_neerlandaise',
    'slovak republic': 'slovaquie',
    'slovakia': 'slovaquie',
    'slovaquie': 'slovaquie',
    'slovenia': 'slovenie',
    'slovénie': 'slovenie',
    'socialist republic of viet nam': 'viet_nam',
    'solomon islands': 'salomon_iles',
    'somalia': 'somalie',
    'somalie': 'somalie',
    'soudan': 'soudan',
    'soudan du sud': 'soudan_du_sud',
    'south africa': 'afrique_du_sud',
    'south georgia and the south sandwich islands': 'georgie_du_sud_et_les_iles_sandwich_du_sud',
    'south korea': 'coree_republique_de',
    'south sudan': 'soudan_du_sud',
    'spain': 'espagne',
    'sri lanka': 'sri_lanka',
    'state of israel': 'israel',
    'state of kuwait': 'koweit',
    'state of qatar': 'qatar',
    'sudan': 'soudan',
    'suisse': 'suisse',
    'sultanate of oman': 'oman',
    'surinam': 'surinam',
    'suriname': 'surinam',
    'suède': 'suede',
    'svalbard and jan mayen': 'svalbard_et_ile_jan_mayen',
    'svalbard et île jan mayen': 'svalbard_et_ile_jan_mayen',
    'sweden': 'suede',
    'swiss confederation': 'suisse',
    'switzerland': 'suisse',
    'syria': 'syrienne_republique_arabe',
    'syrian arab republic': 'syrienne_republique_arabe',
    'syrienne, république arabe': 'syrienne_republique_arabe',
    'sénégal': 'senegal',
    'taiwan': 'taiwan_province_de_chine',
    'taiwan, province of china': 'taiwan_province_de_chine',
    'tanzania': 'tanzanie_republique_unie_de',
    'tanzania, united republic of': 'tanzanie_republique_unie_de',
    'tanzanie, république unie de': 'tanzanie_republique_unie_de',
    'taïwan, province de chine': 'taiwan_province_de_chine',
    'tchad': 'tchad',
    'tchéquie': 'tchequie',
    'terres australes françaises': 'terres_australes_francaises',
    "territoire britannique de l'océan indien": 'territoire_britannique_de_l_ocean_indien',
    'thailand': 'thailande',
    'thaïlande': 'thailande',
    'the state of eritrea': 'erythree',
    'the state of palestine': 'palestine_etat_de',
    'timor oriental': 'timor_oriental',
    'timor-leste': 'timor_oriental',
    'togo': 'togo',
    'togolese republic': 'togo',
    'tokelau': 'tokelau',
    'tonga': 'tonga',
    'trinidad and tobago': 'trinite_et_tobago',
    'trinité-et-tobago': 'trinite_et_tobago',
    'tunisia': 'tunisie',
    'tunisie': 'tunisie',
    'turks and caicos islands': 'iles_turques_et_caiques',
    'tuvalu': 'tuvalu',
    'uganda': 'ouganda',
    'union of the comoros': 'comores',
    'united arab emirates': 'emirats_arabes_unis',
    'united kingdom': 'royaume_uni',
    'united kingdom of great britain and northern ireland': 'royaume_uni',
    'united mexican states': 'mexique',
    'united republic of tanzania': 'tanzanie_republique_unie_de',
    'united states': 'etats_unis',
    'united states minor outlying islands': 'iles_mineures_eloignees_des_etats_unis',
    'united states of america': 'etats_unis',
    'uruguay': 'uruguay',
    'vanuatu': 'vanuatu',
    'venezuela': 'venezuela_republique_bolivarienne_du',
    'venezuela, bolivarian republic of': 'venezuela_republique_bolivarienne_du',
    'viet nam': 'viet_nam',
    'vietnam': 'viet_nam',
    'virgin islands of the united states': 'iles_vierges_etats_unis',
    'virgin islands, british': 'iles_vierges_britanniques',
    'virgin islands, u.s.': 'iles_vierges_etats_unis',
    'viêt nam': 'viet_nam',
    'vénézuela, république bolivarienne du': 'venezuela_republique_bolivarienne_du',
    'wallis and futuna': 'wallis_et_futuna',
    'wallis et futuna': 'wallis_et_futuna',
    'western sahara': 'sahara_occidental',
    'yemen': 'yemen',
    'yémen': 'yemen',
    'zambia': 'zambie',
    'zambie': 'zambie',
    'zimbabwe': 'zimbabwe',
    'åland islands': 'aland_iles',
    'åland, îles': 'aland_iles',
    'égypte': 'egypte',
    'émirats arabes unis': 'emirats_arabes_unis',
    'équateur': 'equateur',
    'érythrée': 'erythree',
    'états-unis': 'etats_unis',
    'éthiopie': 'ethiopie',
    'île bouvet': 'ile_bouvet',
    'île de man': 'ile_de_man',
    'île norfolk': 'ile_norfolk',
    'îles caïmans': 'iles_caimans',
    'îles cook': 'iles_cook',
    'îles féroé': 'iles_feroe',
    'îles heard-et-macdonald': 'iles_heard_et_macdonald',
    'îles mariannes du nord': 'iles_mariannes_du_nord',
    'îles marshall': 'iles_marshall',
    'îles mineures éloignées des états-unis': 'iles_mineures_eloignees_des_etats_unis',
    'îles pitcairn': 'iles_pitcairn',
    'îles turques-et-caïques': 'iles_turques_et_caiques',
    'îles vierges britanniques': 'iles_vierges_britanniques',
    'îles vierges, états-unis': 'iles_vierges_etats_unis',
    'австралия': 'australie',
    'австрия': 'autriche',
    'аландские острова': 'aland_iles',
    'албания': 'albanie',
    'алжир': 'algerie',
    'американские самоа': 'samoa_americaines',
    'ангвилла': 'anguilla',
    'ангола': 'angola',
    'андорра': 'andorre',
    'антарктика': 'antarctique',
    'антигуа и барбуда': 'antigua_et_barbuda',
    'аргентина': 'argentine',
    'аруба': 'aruba',
    'багамы': 'bahamas',
    'бангладеш': 'bangladesh',
    'барбадос': 'barbade',
    'бахрейн': 'bahrein',
    'белиз': 'belize',
    'бельгия': 'belgique',
    'бенин': 'benin',
    'бермуды': 'bermudes',
    'болгария': 'bulgarie',
    'боливарианская республика венесуэла': 'venezuela_republique_bolivarienne_du',
    'боливия': 'bolivie_etat_plurinational_de',
    'бонайре, синт-эстатиус и саба': 'bonaire_saint_eustache_et_saba',
    'босния и герцеговина': 'bosnie_herzegovine',
    'ботсвана': 'botswana',
    'бразилия': 'bresil',
    'британская территория индийского океана': 'territoire_britannique_de_l_ocean_indien',
    'бруней даруссалам': 'brunei_darussalam',
    'буркина-фасо': 'burkina_faso',
    'бурунди': 'burundi',
    'бутан': 'bhoutan',
    'вануату': 'vanuatu',
    'венгрия': 'hongrie',
    'виргинские острова (британия)': 'iles_vierges_britanniques',
    'виргинские острова (сша)': 'iles_vierges_etats_unis',
    'восточный тимор': 'timor_oriental',
    'вьетнам': 'viet_nam',
    'габон': 'gabon',
    'гаити': 'haiti',
    'гайана': 'guyana',
    'гамбия': 'gambie',
    'гана': 'ghana',
    'гваделупа': 'guadeloupe',
    'гватемала': 'guatemala',
    'гвинея': 'guinee',
    'гвинея-бисау': 'guinee_bissau',
    'германия': 'allemagne',
    'гернси': 'guernesey',
    'гибралтар': 'gibraltar',
    'гондурас': 'honduras',
    'гонконг': 'hong_kong',
    'государство-город ватикан': 'saint_siege_etat_de_la_cite_du_vatican',
    'гренада': 'grenade',
    'гренландия': 'groenland',
    'греция': 'grece',
    'гуам': 'guam',
    'дания': 'danemark',
    'демократическая республика конго': 'republique_democratique_du_congo',
    'джерси': 'jersey',
    'джибути': 'djibouti',
    'доминика': 'dominique',
    'доминиканская республика': 'republique_dominicaine',
    'египет': 'egypte',
    'замбия': 'zambie',
    'западная сахара': 'sahara_occidental',
    'зимбабве': 'zimbabwe',
    'израиль': 'israel',
    'индия': 'inde',
    'индонезия': 'indonesie',
    'иордания': 'jordanie',
    'ирак': 'irak',
    'ирландия': 'irlande',
    'исландия': 'islande',
    'испания': 'espagne',
    'италия': 'italie',
    'йемен': 'yemen',
    'кабо-верде': 'cap_vert',
    'каймановы острова': 'iles_caimans',
    'камбоджа': 'cambodge',
    'камерун': 'cameroun',
    'канада': 'canada',
    'катар': 'qatar',
    'кения': 'kenya',
    'кипр': 'chypre',
    'кирибати': 'kiribati',
    'китайская провинция тайвань': 'taiwan_province_de_chine',
    'кокосовые острова': 'cocos_keeling_iles',
    'колумбия': 'colombie',
    'коморы': 'comores',
    'конго': 'republique_du_congo',
    'корейская народно-демократическая республика': 'coree_republique_populaire_democratique_de',
    'коста-рика': 'costa_rica',
    "кот-д'ивуар": 'cote_d_ivoire',
    'куба': 'cuba',
    'кувейт': 'koweit',
    'кюрасао': 'curacao',
    'лаосская народно-демократическая республика': 'lao_republique_democratique_populaire',
    'латвия': 'lettonie',
    'лесото': 'lesotho',
    'либерия': 'liberia',
    'ливан': 'liban',
    'ливия': 'libye',
    'литва': 'lituanie',
    'лихтенштейн': 'liechtenstein',
    'люксембург': 'luxembourg',
    'маврикий': 'maurice',
    'мавритания': 'mauritanie',
    'мадагаскар': 'madagascar',
    'майот': 'mayotte',
    'макао': 'macau',
    'малави': 'malawi',
    'малайзия': 'malaisie',
    'мали': 'mali',
    'мальдивы': 'maldives',
    'мальта': 'malte',
    'марокко': 'maroc',
    'мартиника': 'martinique',
    'маршалловы острова': 'iles_marshall',
    'мексика': 'mexique',
    'мозамбик': 'mozambique',
    'монако': 'monaco',
    'монголия': 'mongolie',
    'монтсеррат': 'montserrat',
    'мьянма': 'birmanie',
    'намибия': 'namibie',
    'науру': 'nauru',
    'непал': 'nepal',
    'нигер': 'niger',
    'нигерия': 'nigeria',
    'нидерланды': 'pays_bas',
    'никарагуа': 'nicaragua',
    'ниуэ': 'nioue',
    'новая зеландия': 'nouvelle_zelande',
    'новая каледония': 'nouvelle_caledonie',
    'норвегия': 'norvege',
    'объединённые арабские эмираты': 'emirats_arabes_unis',
    'оман': 'oman',
    'остров буве': 'ile_bouvet',
    'остров мэн': 'ile_de_man',
    'остров норфолк': 'ile_norfolk',
    'остров рождества': 'christmas_ile',
    'остров святой елены, остров вознесения и тристан-да-кунья': 'sainte_helene_ascension_et_tristan_da_cunha',
    'остров херд и острова макдональд': 'iles_heard_et_macdonald',
    'острова кука': 'iles_cook',
    'острова северной марианы': 'iles_mariannes_du_nord',
    'острова туркс и каикос': 'iles_turques_et_caiques',
    'пакистан': 'pakistan',
    'палау': 'palaos',
    'палестина': 'palestine_etat_de',
    'панама': 'panama',
    'папуа — новая гвинея': 'papouasie_nouvelle_guinee',
    'парагвай': 'paraguay',
    'перу': 'perou',
    'питкэрн': 'iles_pitcairn',
    'польша': 'pologne',
    'португалия': 'portugal',
    'пуэрто-рико': 'porto_rico',
    'республика корея': 'coree_republique_de',
    'реюньон': 'reunion_ile_de_la',
    'руанда': 'rwanda',
    'румыния': 'roumanie',
    'сальвадор': 'salvador',
    'самоа': 'samoa',
    'сан-марино': 'saint_marin',
    'сан-томе и принсипи': 'sao_tome_et_principe',
    'саудовская аравия': 'arabie_saoudite',
    'северная македония': 'macedoine_du_nord',
    'сейшелы': 'seychelles',
    'сен-бартельми': 'saint_barthelemy',
    'сен-мартен (франция)': 'saint_martin_partie_francaise',
    'сен-пьер и микелон': 'saint_pierre_et_miquelon',
    'сенегал': 'senegal',
    'сент-винсент и гренадины': 'saint_vincent_et_les_grenadines',
    'сент-китс и невис': 'saint_christophe_et_nieves',
    'сент-люсия': 'sainte_lucie',
    'сербия': 'serbie',
    'сингапур': 'singapour',
    'синт-мартен (голландская часть)': 'saint_martin_partie_neerlandaise',
    'сирийская арабская республика': 'syrienne_republique_arabe',
    'словакия': 'slovaquie',
    'словения': 'slovenie',
    'соединенные штаты малых удаленных островов': 'iles_mineures_eloignees_des_etats_unis',
    'соединённое королевство': 'royaume_uni',
    'соединённые штаты': 'etats_unis',
    'соломоновы острова': 'salomon_iles',
    'сомали': 'somalie',
    'судан': 'soudan',
    'суринам': 'surinam',
    'сьерра-леоне': 'sierra_leone',
    'таиланд': 'thailande',
    'танзания': 'tanzanie_republique_unie_de',
    'токелау': 'tokelau',
    'тонга': 'tonga',
    'тринидад и тобаго': 'trinite_et_tobago',
    'тувалу': 'tuvalu',
    'тунис': 'tunisie',
    'уганда': 'ouganda',
    'уоллес и футана': 'wallis_et_futuna',
    'уругвай': 'uruguay',
    'фарерские острова': 'iles_feroe',
    'федеративные штаты микронезии': 'micronesie_etats_federes_de',
    'фиджи': 'fidji',
    'филиппины': 'philippines',
    'финляндия': 'finlande',
    'фолклендские (мальвинские) острова': 'malouines_iles_falkland',
    'франция': 'france',
    'французская гвиана': 'guyane_francaise',
    'французская полинезия': 'polynesie_francaise',
    'французские южные территории': 'terres_australes_francaises',
    'хорватия': 'croatie',
    'центрально-африканская республика': 'republique_centrafricaine',
    'черногория': 'montenegro',
    'чехия': 'tchequie',
    'чили': 'chili',
    'швейцария': 'suisse',
    'швеция': 'suede',
    'шпицберген и ян-майен': 'svalbard_et_ile_jan_mayen',
    'шри-ланка': 'sri_lanka',
    'эквадор': 'equateur',
    'экваториальная гвинея': 'guinee_equatoriale',
    'эритрея': 'erythree',
    'эсватини': 'eswatini',
    'эстония': 'estonie',
    'эфиопия': 'ethiopie',
    'южная африка': 'afrique_du_sud',
    'южная джорджия и южные сандвичевы острова': 'georgie_du_sud_et_les_iles_sandwich_du_sud',
    'южный судан': 'soudan_du_sud',
    'ямайка': 'jamaique',
    'япония': 'japon',
}

# identifiant -> libellé affichable
PAYS_MONDE_LIBELLES: dict[str, str] = {
    'afrique_du_sud': 'Afrique du Sud',
    'aland_iles': 'Åland, Îles',
    'albanie': 'Albanie',
    'algerie': 'Algérie',
    'allemagne': 'Allemagne',
    'andorre': 'Andorre',
    'angola': 'Angola',
    'anguilla': 'Anguilla',
    'antarctique': 'Antarctique',
    'antigua_et_barbuda': 'Antigua-et-Barbuda',
    'arabie_saoudite': 'Arabie saoudite',
    'argentine': 'Argentine',
    'aruba': 'Aruba',
    'australie': 'Australie',
    'autriche': 'Autriche',
    'bahamas': 'Bahamas',
    'bahrein': 'Bahreïn',
    'bangladesh': 'Bangladesh',
    'barbade': 'Barbade',
    'belgique': 'Belgique',
    'belize': 'Belize',
    'benin': 'Bénin',
    'bermudes': 'Bermudes',
    'bhoutan': 'Bhoutan',
    'birmanie': 'Birmanie',
    'bolivie_etat_plurinational_de': 'Bolivie, état plurinational de',
    'bonaire_saint_eustache_et_saba': 'Bonaire, Saint-Eustache et Saba',
    'bosnie_herzegovine': 'Bosnie-Herzégovine',
    'botswana': 'Botswana',
    'bresil': 'Brésil',
    'brunei_darussalam': 'Brunéi Darussalam',
    'bulgarie': 'Bulgarie',
    'burkina_faso': 'Burkina Faso',
    'burundi': 'Burundi',
    'cambodge': 'Cambodge',
    'cameroun': 'Cameroun',
    'canada': 'Canada',
    'cap_vert': 'Cap-Vert',
    'chili': 'Chili',
    'christmas_ile': 'Christmas, Île',
    'chypre': 'Chypre',
    'cocos_keeling_iles': 'Cocos (Keeling), Îles',
    'colombie': 'Colombie',
    'comores': 'Comores',
    'coree_republique_de': 'Corée, République de',
    'coree_republique_populaire_democratique_de': 'Corée, République populaire démocratique de',
    'costa_rica': 'Costa Rica',
    'cote_d_ivoire': "Côte d'Ivoire",
    'croatie': 'Croatie',
    'cuba': 'Cuba',
    'curacao': 'Curaçao',
    'danemark': 'Danemark',
    'djibouti': 'Djibouti',
    'dominique': 'Dominique',
    'egypte': 'Égypte',
    'emirats_arabes_unis': 'Émirats arabes unis',
    'equateur': 'Équateur',
    'erythree': 'Érythrée',
    'espagne': 'Espagne',
    'estonie': 'Estonie',
    'eswatini': 'Eswatini',
    'etats_unis': 'États-Unis',
    'ethiopie': 'Éthiopie',
    'fidji': 'Fidji',
    'finlande': 'Finlande',
    'france': 'France',
    'gabon': 'Gabon',
    'gambie': 'Gambie',
    'georgie_du_sud_et_les_iles_sandwich_du_sud': 'Géorgie du Sud et les îles Sandwich du Sud',
    'ghana': 'Ghana',
    'gibraltar': 'Gibraltar',
    'grece': 'Grèce',
    'grenade': 'Grenade',
    'groenland': 'Groënland',
    'guadeloupe': 'Guadeloupe',
    'guam': 'Guam',
    'guatemala': 'Guatemala',
    'guernesey': 'Guernesey',
    'guinee': 'Guinée',
    'guinee_bissau': 'Guinée-Bissau',
    'guinee_equatoriale': 'Guinée Équatoriale',
    'guyana': 'Guyana',
    'guyane_francaise': 'Guyane française',
    'haiti': 'Haïti',
    'honduras': 'Honduras',
    'hong_kong': 'Hong Kong',
    'hongrie': 'Hongrie',
    'ile_bouvet': 'Île Bouvet',
    'ile_de_man': 'Île de Man',
    'ile_norfolk': 'Île Norfolk',
    'iles_caimans': 'Îles Caïmans',
    'iles_cook': 'Îles Cook',
    'iles_feroe': 'Îles Féroé',
    'iles_heard_et_macdonald': 'Îles Heard-et-MacDonald',
    'iles_mariannes_du_nord': 'Îles Mariannes du Nord',
    'iles_marshall': 'Îles Marshall',
    'iles_mineures_eloignees_des_etats_unis': 'Îles mineures éloignées des États-Unis',
    'iles_pitcairn': 'Îles Pitcairn',
    'iles_turques_et_caiques': 'Îles Turques-et-Caïques',
    'iles_vierges_britanniques': 'Îles Vierges britanniques',
    'iles_vierges_etats_unis': 'Îles Vierges, États-Unis',
    'inde': 'Inde',
    'indonesie': 'Indonésie',
    'irak': 'Irak',
    'irlande': 'Irlande',
    'islande': 'Islande',
    'israel': 'Israël',
    'italie': 'Italie',
    'jamaique': 'Jamaïque',
    'japon': 'Japon',
    'jersey': 'Jersey',
    'jordanie': 'Jordanie',
    'kenya': 'Kenya',
    'kiribati': 'Kiribati',
    'koweit': 'Koweït',
    'lao_republique_democratique_populaire': 'Lao, République démocratique populaire',
    'lesotho': 'Lesotho',
    'lettonie': 'Lettonie',
    'liban': 'Liban',
    'liberia': 'Libéria',
    'libye': 'Libye',
    'liechtenstein': 'Liechtenstein',
    'lituanie': 'Lituanie',
    'luxembourg': 'Luxembourg',
    'macau': 'Macau',
    'macedoine_du_nord': 'Macédoine du Nord',
    'madagascar': 'Madagascar',
    'malaisie': 'Malaisie',
    'malawi': 'Malawi',
    'maldives': 'Maldives',
    'mali': 'Mali',
    'malouines_iles_falkland': 'Malouines, Îles (Falkland)',
    'malte': 'Malte',
    'maroc': 'Maroc',
    'martinique': 'Martinique',
    'maurice': 'Maurice',
    'mauritanie': 'Mauritanie',
    'mayotte': 'Mayotte',
    'mexique': 'Mexique',
    'micronesie_etats_federes_de': 'Micronésie, États fédérés de',
    'monaco': 'Monaco',
    'mongolie': 'Mongolie',
    'montenegro': 'Monténégro',
    'montserrat': 'Montserrat',
    'mozambique': 'Mozambique',
    'namibie': 'Namibie',
    'nauru': 'Nauru',
    'nepal': 'Népal',
    'nicaragua': 'Nicaragua',
    'niger': 'Niger',
    'nigeria': 'Nigeria',
    'nioue': 'Nioue',
    'norvege': 'Norvège',
    'nouvelle_caledonie': 'Nouvelle-Calédonie',
    'nouvelle_zelande': 'Nouvelle-Zélande',
    'oman': 'Oman',
    'ouganda': 'Ouganda',
    'pakistan': 'Pakistan',
    'palaos': 'Palaos',
    'palestine_etat_de': 'Palestine, État de',
    'panama': 'Panama',
    'papouasie_nouvelle_guinee': 'Papouasie-Nouvelle-Guinée',
    'paraguay': 'Paraguay',
    'pays_bas': 'Pays-Bas',
    'perou': 'Pérou',
    'philippines': 'Philippines',
    'pologne': 'Pologne',
    'polynesie_francaise': 'Polynésie française',
    'porto_rico': 'Porto Rico',
    'portugal': 'Portugal',
    'qatar': 'Qatar',
    'republique_centrafricaine': 'République centrafricaine',
    'republique_democratique_du_congo': 'République démocratique du Congo',
    'republique_dominicaine': 'République dominicaine',
    'republique_du_congo': 'République du Congo',
    'reunion_ile_de_la': 'Réunion, Île de la',
    'roumanie': 'Roumanie',
    'royaume_uni': 'Royaume-Uni',
    'rwanda': 'Rwanda',
    'sahara_occidental': 'Sahara occidental',
    'saint_barthelemy': 'Saint-Barthélemy',
    'saint_christophe_et_nieves': 'Saint-Christophe-et-Niévès',
    'saint_marin': 'Saint-Marin',
    'saint_martin_partie_francaise': 'Saint-Martin (partie française)',
    'saint_martin_partie_neerlandaise': 'Saint-Martin (partie néerlandaise)',
    'saint_pierre_et_miquelon': 'Saint-Pierre-et-Miquelon',
    'saint_siege_etat_de_la_cite_du_vatican': 'Saint-Siège (état de la cité du Vatican)',
    'saint_vincent_et_les_grenadines': 'Saint-Vincent-et-les-Grenadines',
    'sainte_helene_ascension_et_tristan_da_cunha': 'Sainte-Hélène, Ascension et Tristan da Cunha',
    'sainte_lucie': 'Sainte-Lucie',
    'salomon_iles': 'Salomon, Îles',
    'salvador': 'Salvador',
    'samoa': 'Samoa',
    'samoa_americaines': 'Samoa américaines',
    'sao_tome_et_principe': 'Sao Tomé-et-Principe',
    'senegal': 'Sénégal',
    'serbie': 'Serbie',
    'seychelles': 'Seychelles',
    'sierra_leone': 'Sierra Leone',
    'singapour': 'Singapour',
    'slovaquie': 'Slovaquie',
    'slovenie': 'Slovénie',
    'somalie': 'Somalie',
    'soudan': 'Soudan',
    'soudan_du_sud': 'Soudan du Sud',
    'sri_lanka': 'Sri Lanka',
    'suede': 'Suède',
    'suisse': 'Suisse',
    'surinam': 'Surinam',
    'svalbard_et_ile_jan_mayen': 'Svalbard et île Jan Mayen',
    'syrienne_republique_arabe': 'Syrienne, République arabe',
    'taiwan_province_de_chine': 'Taïwan, province de Chine',
    'tanzanie_republique_unie_de': 'Tanzanie, République unie de',
    'tchad': 'Tchad',
    'tchequie': 'Tchéquie',
    'terres_australes_francaises': 'Terres australes françaises',
    'territoire_britannique_de_l_ocean_indien': "Territoire britannique de l'océan Indien",
    'thailande': 'Thaïlande',
    'timor_oriental': 'Timor oriental',
    'togo': 'Togo',
    'tokelau': 'Tokelau',
    'tonga': 'Tonga',
    'trinite_et_tobago': 'Trinité-et-Tobago',
    'tunisie': 'Tunisie',
    'tuvalu': 'Tuvalu',
    'uruguay': 'Uruguay',
    'vanuatu': 'Vanuatu',
    'venezuela_republique_bolivarienne_du': 'Vénézuela, république bolivarienne du',
    'viet_nam': 'Viêt Nam',
    'wallis_et_futuna': 'Wallis et Futuna',
    'yemen': 'Yémen',
    'zambie': 'Zambie',
    'zimbabwe': 'Zimbabwe',
}
